// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using appointment_details.database;

#nullable disable

namespace prescription_management.database.migrations
{
    [DbContext(typeof(postgresHealthCareDbContext))]
    [Migration("20241216180737_pending_changes")]
    partial class pending_changes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("appointment_details.database.models.AppointmentDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentBookedOn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("appointment_booked_on");

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("DATE")
                        .HasColumnName("appointment_date");

                    b.Property<string>("AppointmentStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("appointment_status");

                    b.Property<string>("AppointmentTimeOfDay")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("appointment_time_of_day");

                    b.Property<string>("DoctorId")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("doctor_id");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("patient_id");

                    b.HasKey("Id");

                    b.ToTable("appointment_details");
                });
#pragma warning restore 612, 618
        }
    }
}
