version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5001"
    depends_on:
      - redis

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6378:6379"
